### ISSUE TITLE
BUG: Incorrect working directory

### ISSUE THREAD

**Issue by carrascomj** [biosustain/Maud#371]
Hello!

Not super sure why but [this instantiation of `CmdStanModel` at sampling](https://github.com/biosustain/Maud/blob/a750b48b1a7c2cbc454e464c0c8125ea7250a118/src/maud/sampling.py#L136) changes the current working directory and makes `maud simulate`/`sample` fail.

### Debug info

OS: Linux
Python 3.9
Installed through on a fresh virtualenv with [virtuaenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/) with

```
pip install "git+https://github.com/biosustain/Maud#egg=maud"
install_cmdstan
```

(commit a750b48b1)

<details>
  <summary>maud simulate data traceback</summary>

```
Creating output directory: ./maud_output_sim-poc_cauto-20220103113411
Copying user input from data to ./maud_output_sim-poc_cauto-20220103113411/user_input
INFO:cmdstanpy:found newer exe file, not recompiling
Traceback (most recent call last):
  File "/home/georg/.virtualenvs/maud/bin/maud", line 33, in <module>
    sys.exit(load_entry_point('maud', 'console_scripts', 'maud')())
  File "/home/georg/.virtualenvs/maud/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/georg/.virtualenvs/maud/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/georg/.virtualenvs/maud/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/georg/.virtualenvs/maud/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/georg/.virtualenvs/maud/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/georg/GIT/Maud/src/maud/cli.py", line 188, in simulate_command
    click.echo(simulate(data_path, output_dir, n))
  File "/home/georg/GIT/Maud/src/maud/cli.py", line 162, in simulate
    stanfit = sampling.simulate(mi, samples_path, n)
  File "/home/georg/GIT/Maud/src/maud/sampling.py", line 106, in simulate
    return _sample_given_config(mi, output_dir, config)
  File "/home/georg/GIT/Maud/src/maud/sampling.py", line 143, in _sample_given_config
    return model.sample(data=input_filepath, **config)
  File "/home/georg/.virtualenvs/maud/lib/python3.9/site-packages/cmdstanpy/model.py", line 921, in sample
    with MaybeDictToFilePath(data, inits) as (_data, _inits):
  File "/home/georg/.virtualenvs/maud/lib/python3.9/site-packages/cmdstanpy/utils.py", line 1353, in __init__
    raise ValueError("File doesn't exist {}".format(obj))
ValueError: File doesn't exist ./maud_output_sim-poc_cauto-20220103113411/samples/input_data.json
INFO:cmdstanpy:deleting tmpfiles dir: /tmp/tmpvlc8qmr8
INFO:cmdstanpy:done
```
</details>

I _think_ I had problems before with this, it is not from recent commits.

### Workaround 

At [`src/maud/sampling.py`](https://github.com/biosustain/Maud/blob/a750b48b1a7c2cbc454e464c0c8125ea7250a118/src/maud/sampling.py#L136):

````diff
+   curr_dir = os.getcwd()
    model = cmdstanpy.CmdStanModel(
        stan_file=stan_program_filepath,
        stanc_options=stanc_options,
       cpp_options=cpp_options,
    )
+   os.chdir(curr_dir)
```

**Comment by teddygroves** [comment]
I think this is a bug in cmdstanpy that was fixed here (but the fix hasn't been released yet): https://github.com/stan-dev/cmdstanpy/pull/507. 

I think installing the latest version from github by changing [this line](https://github.com/biosustain/Maud/blob/a750b48b1a7c2cbc454e464c0c8125ea7250a118/setup.cfg#L38) as follows should work as well:

before:
```
    cmdstanpy >=0.9.2
```

after:
```
    cmdstanpy@git+https://github.com/stan-dev/cmdstanpy.git@develop
```
I made a quick branch doing this here https://github.com/biosustain/Maud/pull/372/.

**Comment by carrascomj** [comment]
Thanks, Teddy! Pip-installing from the branch works as expected, feel free to close this.

**Comment by teddygroves** [comment]
(reopening until the pr goes through)
