### ISSUE TITLE
Generated idata fails to be deserialized

### ISSUE THREAD

**Issue by carrascomj** [biosustain/Maud#421]
I have two `idata.json` outputs generated by `maud sample` (`maud-metabolic-models==0.4.0.2`) and none of them can be read back to memory.

Traceback:

```python
>>> idata = az.from_json("idata.json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jorge/.virtualenvs/maud/lib/python3.9/site-packages/arviz/data/io_json.py", line 29, in from_json
    idata_dict = json.load(file)
ujson.JSONDecodeError: Unexpected character found when decoding 'Infinity'
```

Without `ujson` (using the stdlib `json` module), it also fails but with a more cryptic error.

**Comment by carrascomj** [comment]
As a workaround

```python
from glob import glob
from maud.loading_maud_inputs import load_maud_input
from maud.getting_idatas import get_idata

mi = load_maud_input("user_input")
idata = get_idata(glob("samples/*csv"), mi, "train")
```

works fine.
